name: won-games
services:
  db:
    container_name: db
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    image: postgres:15-alpine
    env_file:
      - ./apps/strapi/.env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/ #using a volume
      #- ./data:/var/lib/postgresql/data/ # if you want to use a bind folder
    ports:
      - "5432:5432"
    networks:
      - strapi

  strapi:
    container_name: strapi
    build:
      context: .
      dockerfile: ./apps/strapi/Dockerfile
    env_file:
      - ./apps/strapi/.env
    volumes:
      - ./config:/opt/app/config
      - ./src:/opt/app/src
      - ./turbo.json:/opt/turbo.json
      - ./package.json:/opt/package.json
      - ./yarn.lock:/opt/yarn.lock
      - ./.env:/opt/app/.env
      - ./public/uploads:/opt/app/public/uploads
    networks:
      - strapi
    depends_on:
      - db

  strapiAdminer:
    container_name: strapiAdminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
    networks:
      - strapi
    depends_on:
      - db

volumes:
  strapi-data:

networks:
  strapi:
    name: Strapi
    driver: bridge
